/***************************************************************************//**
 * @file monarco_sdc.h
 * @brief LibMonarco - Service Data Channel (SDC) definitions
 *******************************************************************************
 * @section License
 * Copyright REX Controls s.r.o. http://www.rexcontrols.com
 * Author: Vlastimil Setka
 * This file is covered by the BSD 3-Clause License
 *   see LICENSE.txt in the root directory of this project
 *   or <https://opensource.org/licenses/BSD-3-Clause>
 *******************************************************************************/

#ifndef LIBMONARCO_SDC_H_
#define LIBMONARCO_SDC_H_

/* COUNTER Configuration Flags */

#define MONARCO_SDC_COUNTER_MODE__SHIFT 0
#define MONARCO_SDC_COUNTER_MODE__MASK (0x7 << MONARCO_SDC_COUNTER_MODE__SHIFT)
#define MONARCO_SDC_COUNTER_MODE__MAX 2
#define MONARCO_SDC_COUNTER_MODE_OFF (0 << MONARCO_SDC_COUNTER_MODE__SHIFT)
#define MONARCO_SDC_COUNTER_MODE_PCNT (1 << MONARCO_SDC_COUNTER_MODE__SHIFT)
#define MONARCO_SDC_COUNTER_MODE_QUAD (2 << MONARCO_SDC_COUNTER_MODE__SHIFT)

#define MONARCO_SDC_COUNTER_CTRL__SHIFT 3
#define MONARCO_SDC_COUNTER_CTRL__MASK (0x7 << MONARCO_SDC_COUNTER_CTRL__SHIFT)
#define MONARCO_SDC_COUNTER_CTRL__MAX 1
#define MONARCO_SDC_COUNTER_CTRL_UP (0 << MONARCO_SDC_COUNTER_CTRL__SHIFT)
#define MONARCO_SDC_COUNTER_CTRL_EXT (1 << MONARCO_SDC_COUNTER_CTRL__SHIFT) /* direction selectable by B input, high = down-counting */

#define MONARCO_SDC_COUNTER_EDGE__SHIFT 6
#define MONARCO_SDC_COUNTER_EDGE__MASK (0x3 << MONARCO_SDC_COUNTER_EDGE__SHIFT)
#define MONARCO_SDC_COUNTER_EDGE__MAX 2
#define MONARCO_SDC_COUNTER_EDGE_RISE (0 << MONARCO_SDC_COUNTER_EDGE__SHIFT)
#define MONARCO_SDC_COUNTER_EDGE_FALL (1 << MONARCO_SDC_COUNTER_EDGE__SHIFT)
#define MONARCO_SDC_COUNTER_EDGE_BOTH (2 << MONARCO_SDC_COUNTER_EDGE__SHIFT)

#define MONARCO_SDC_COUNTER_CAPTURE__SHIFT 8
#define MONARCO_SDC_COUNTER_CAPTURE__MASK (0x3 << MONARCO_SDC_COUNTER_CAPTURE__SHIFT)
#define MONARCO_SDC_COUNTER_CAPTURE__MAX 3
#define MONARCO_SDC_COUNTER_CAPTURE_OFF (0 << MONARCO_SDC_COUNTER_CAPTURE__SHIFT)
#define MONARCO_SDC_COUNTER_CAPTURE_RISE (1 << MONARCO_SDC_COUNTER_CAPTURE__SHIFT)
#define MONARCO_SDC_COUNTER_CAPTURE_FALL (2 << MONARCO_SDC_COUNTER_CAPTURE__SHIFT)
#define MONARCO_SDC_COUNTER_CAPTURE_BOTH (3 << MONARCO_SDC_COUNTER_CAPTURE__SHIFT)

/* CONFIG1 Register Flags*/

#define MONARCO_SDC_CONFIG1_RS485TERM (1 << 0)
#define MONARCO_SDC_CONFIG1_AI1CL (1 << 1)
#define MONARCO_SDC_CONFIG1_AI2CL (1 << 2)

/* RS485 Mode Register */

#define MONARCO_SDC_RS485_MODE_PARITY__SHIFT 0
#define MONARCO_SDC_RS485_MODE_PARITY_NONE (0 << MONARCO_SDC_RS485_MODE_PARITY__SHIFT)
#define MONARCO_SDC_RS485_MODE_PARITY_EVEN (1 << MONARCO_SDC_RS485_MODE_PARITY__SHIFT)
#define MONARCO_SDC_RS485_MODE_PARITY_ODD (2 << MONARCO_SDC_RS485_MODE_PARITY__SHIFT)

#define MONARCO_SDC_RS485_MODE_DATABITS__SHIFT 3
#define MONARCO_SDC_RS485_MODE_DATABITS_5 (0 << MONARCO_SDC_RS485_MODE_DATABITS__SHIFT)
#define MONARCO_SDC_RS485_MODE_DATABITS_6 (1 << MONARCO_SDC_RS485_MODE_DATABITS__SHIFT)
#define MONARCO_SDC_RS485_MODE_DATABITS_7 (2 << MONARCO_SDC_RS485_MODE_DATABITS__SHIFT)
#define MONARCO_SDC_RS485_MODE_DATABITS_8 (3 << MONARCO_SDC_RS485_MODE_DATABITS__SHIFT)

#define MONARCO_SDC_RS485_MODE_STOPBITS__SHIFT 5
#define MONARCO_SDC_RS485_MODE_STOPBITS_0_5 (0 << MONARCO_SDC_RS485_MODE_STOPBITS__SHIFT)
#define MONARCO_SDC_RS485_MODE_STOPBITS_1_0 (1 << MONARCO_SDC_RS485_MODE_STOPBITS__SHIFT)
#define MONARCO_SDC_RS485_MODE_STOPBITS_1_5 (2 << MONARCO_SDC_RS485_MODE_STOPBITS__SHIFT)
#define MONARCO_SDC_RS485_MODE_STOPBITS_2_0 (3 << MONARCO_SDC_RS485_MODE_STOPBITS__SHIFT)

#define MONARCO_SDC_RS485_DEFAULT_BAUDRATE 96
#define MONARCO_SDC_RS485_DEFAULT_MODE ((MONARCO_SDC_RS485_MODE_PARITY_NONE) | (MONARCO_SDC_RS485_MODE_DATABITS_8) | (MONARCO_SDC_RS485_MODE_STOPBITS_1_0))

#endif
